#!/bin/bash
#SBATCH -p gpu --gpus=2 -C a100-80gb -n 24  -N 1 -t 36:0:0

export OMP_NUM_THREADS=4

source ~/anaconda3/etc/profile.d/conda.sh
conda activate gptLY
cd ~/projects/microcosm
python -m torch.distributed.launch --master_port $MASTER_PORT --nproc_per_node 2 mroberta_xslorenz_sweep_agent_ds_2gpu.py --sweepid  4g7krj82 