#!/bin/bash
#SBATCH -p gpu --gpus=2 -C a100-80gb -n 24  -N 1 -t 36:0:0

export OMP_NUM_THREADS=4

source ~/anaconda3/etc/profile.d/conda.sh
conda activate gptLY
cd ~/projects/microcosm
python -m torch.distributed.launch --master_port $SLURM_JOB_ID --nproc_per_node $SLURM_GPUS_PER_NODE \
         mroberta_xslorenz_sweep_agent.py --sweep_id  4g7krj82