#!/bin/bash
#SBATCH -p gpu --gpus=2 -C a100-40gb -n 16  -N 1 -t 72:0:0

export OMP_NUM_THREADS=10
export TRANSFORMERS_CACHE=/mnt/home/sgolkar/projects/microcosm/cache

source ~/anaconda3/etc/profile.d/conda.sh
conda activate gptLY
cd ~/projects/microcosm/KCroberta_mlp

master_node=$SLURMD_NODENAME

torchrun --nnodes 1 \
        --nproc_per_node 2 \
        --rdzv_id $SLURM_JOB_ID \
        --rdzv_backend c10d \
        --rdzv_endpoint $master_node:29412 \
        KCroberta_mlp_xslorenz_sweep_agent.py --sweep_id 5tmp2oca